export const SET_LIST = "SET_LIST";
export const FETCH_DONOR_LIST = "FETCH_DONOR_LIST";
export const SET_DONOR_LIST = "SET_DONOR_LIST";
export const FETCH_PATIENT_LIST = "FETCH_PATIENT_LIST";
export const SET_PATIENT_LIST = "SET_PATIENT_LIST";
export const FETCH_ORGANIZATION_LIST = "FETCH_PATIENT_LIST";
export const SET_ORGANIZATION_LIST = "SET_PATIENT_LIST";
export const FETCH_REQUEST_LIST = "FETCH_PATIENT_LIST";
export const SET_REQUEST_LIST = "SET_PATIENT_LIST";


