export const SET_LIST = "SET_LIST";
export const FETCH_DONOR_LIST = "FETCH_DONOR_LIST";
export const SET_DONOR_LIST = "SET_DONOR_LIST";
export const FETCH_PATIENT_LIST = "FETCH_PATIENT_LIST";
export const SET_PATIENT_LIST = "SET_PATIENT_LIST";
export const FETCH_ORGANIZATION_LIST = "FETCH_PATIENT_LIST";
export const SET_ORGANIZATION_LIST = "SET_PATIENT_LIST";
export const FETCH_REQUEST_LIST = "FETCH_PATIENT_LIST";
export const SET_REQUEST_LIST = "SET_PATIENT_LIST";

export const CREATE_ORGANIZATION = "CREATE_ORGANIZATION";
export const SUCCESS_CREATE_ORGANIZATION = "SUCCESS_CREATE_ORGANIZATION";

export const CREATE_REQUEST = "CREATE_REQUEST";
export const SUCCESS_CREATE_REQUEST = "SUCCESS_CREATE_REQUEST";

export const CREATE_PATIENT = "CREATE_PATIENT";
export const SUCCESS_CREATE_PATIENT = "SUCCESS_CREATE_DONOR";

export const CREATE_DONOR = "CREATE_PATIENT";
export const SUCCESS_CREATE_DONOR = "SUCCESS_CREATE_DONOR";

